- name: Site Credentials
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Add Site Credential
    uri:
      url: "{{ nexpose_base_api }}/sites/{{ site_id }}/site_credentials"
      method: POST
      user: "{{ nexpose_username }}"
      password: "{{ nexpose_password }}"
      force_basic_auth: yes
      validate_certs: no
      headers:
        Content-Type: application/json
        Accept: application/json
      body: "{{ lookup('template','templates/add_site_credential.json.j2') }}"
      body_format: json
      return_content: yes
    register: add_site_credential
